### ISSUE TITLE
Intermittent “Invalid Address” issue with Apple Pay in version 3.1.4

### ISSUE THREAD

**Issue by pjv** [fluid-checkout/fluid-checkout#355] opened 2024-02-22 18:38 UTC
Running Fluid Checkout on a busy site, some customers are getting an “Invalid address” error when trying to check out with Apple Pay. Other customers are able to check out with Apple Pay with no problem. The error looks like this:

<img width="431" alt="SCR-20240222-lhty" src="https://github.com/fluid-checkout/fluid-checkout/assets/327716/7ccd2d92-bc95-4816-989b-ef33d823dd39">

This site uses the (recommended by you) plugin “Payment Plugins for Stripe WooCommerce” to provide the Apple Pay integration.

We like Fluid Checkout but have had to disable it on the site for now. Hoping you can address this issue and we can re-activate it. If we get the lite version of the plugin working without issues we will certainly be upgrading to pro in order to have the integrated theming for the cart and thank you pages.

**Comment by diegoversiani** [comment] 2024-02-24 07:37
Hi @pjv,

There is a know issue with using express payment methods such as Apple Pay and Google Pay if the checkout form have some fields which are required, such as the shipping phone field, and the saved address on the customer's Apple Pay or Google Pay account does not have that information. This might also happen with other types of fields on the checkout form.

Without knowing the exact address of the customer being passed from their Apple Pay account, it is difficult to know if that is the case here.

See more about this on our documentation (link below) and although we only mention this issue with the Stripe plugin, this also applies to other similar payment gateway plugins:
https://fluidcheckout.com/docs/feature-express-checkout/#compat-woocommerce-stripe-gateway

1. Does this only happen when Fluid Checkout is active?

I'm closing this ticket for now. We'll be disabling the ability to create issues here on Github, please use our website to open [new support tickets](https://fluidcheckout.com/support/).

Best,
Diego.

**Closed by diegoversiani** 2024-02-24 07:37 UTC

**Comment by diegoversiani** [comment] 2024-02-26 10:08
Hi @pjv,

Thanks for pointing that out, we'll revise the content to clear any confusion.

The highlighted text in your screenshot is related to having any extra required fields which are not provided by Apple Pay to your WooCommerce store. The plugin Payment Plugins for Stripe WooCommerce seem to be able to handle these cases a bit better.

Please note a few things:

- The documentation I linked before is related to a feature that is only available with Fluid Checkout PRO, which displays the express checkout buttons at the top of the page. Although, these payment methods should also work with Fluid Checkout Lite unless there are any compatibility issues we have not solved yet.

- In any case, Fluid Checkout is not responsible for processing any payment information returned from those payment gateways (Apple Pay, Google Pay, etc...), payment information is only handled by the respective payment gateways plugins (in this case the Payment Plugins for Stripe WooCommerce).

- If there is any compatibility issues caused by Fluid Checkout, the customer should be able to complete the purchase when Fluid Checkout is not activated.

1. Does this only happen when Fluid Checkout is active?

- The error we mention in our documentation might be different than the one you reported, and without knowing the address passed from Apple Pay to your WooCommerce store, we cannot know if the required shipping phone field or other extra required field is causing the payment to fail.

2. Does the customer address have all the required field on your checkout page? If the shipping phone field is required on your checkout page, does the customer have a phone number saved to their shipping address on their Apple Pay account? Are there any other extra required fields on your checkout page?

- The error you reported "[Shipping] Invalid address" happens on the Apple Pay interface, so it seems the information has not yet been passed into your WooCommerce store. And, as mentioned above, the plugin responsible for handling that information would be the payment gateway plugin.

- I did a quick search and found that the error "[Shipping] Invalid address" might be related to the address information to the customer's Apple Pay account might not match their credit card, or because there is a mismatch of the address country to the region of the customer's Apple account:
--> https://discussions.apple.com/thread/252554972?answerId=254824589022&sortBy=best#254824589022
--> https://discussions.apple.com/thread/251599919?sortBy=best
And this one on Shopify's Community forum:
--> https://community.shopify.com/c/payments-shipping-and/apple-pay-keep-showing-invalid-shipping-address/m-p/1209226

I'm closing this ticket for now. We'll be disabling the ability to create issues here on Github, please **use our website** to open [new support tickets](https://fluidcheckout.com/support/).

Best,
Diego.
